name: Build and Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: version
        run: echo "version=$(date +'%Y.%m.%d.%H%M')" >> "$GITHUB_OUTPUT"
      - name: Generate Release Notes
        id: release_notes
        run: |
          # Get the last two commits to find the latest changes
          COMMITS=$(git log -2 --pretty=format:"%s")
          
          # Create release notes content
          cat << EOF > release_notes.md
          # Release v${{ steps.version.outputs.version }}
          
          ## What's Changed
          
          $(git log -1 --pretty=format:"%b")
          
          ## Recent Changes
          $(git log -10 --pretty=format:"* %s")
          
          ## Build Information
          * This release includes builds for:
            * Linux (x86_64)
            * macOS (ARM64)
          
          ## Installation
          Download the appropriate binary for your system and extract it:
          
          ### Linux
          ```bash
          tar xzf llm_dataset_builder-linux-x86_64.tar.gz
          ```
          
          ### macOS (Apple Silicon)
          ```bash
          tar xzf llm_dataset_builder-darwin-arm64.tar.gz
          ```
          EOF
          
          # Store release notes for the release step
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
            binary_path: target/release/llm_dataset_builder
            asset_name: llm_dataset_builder-linux-x86_64

          - os: macos-14
            target: aarch64-apple-darwin
            name: darwin-arm64
            binary_path: target/release/llm_dataset_builder
            asset_name: llm_dataset_builder-darwin-arm64

          # Commented out for now to reduce build time
          # - os: macos-14
          #   target: x86_64-apple-darwin
          #   name: darwin-x86_64
          #   binary_path: target/release/llm_dataset_builder
          #   asset_name: llm_dataset_builder-darwin-x86_64

          # - os: windows-2022
          #   target: x86_64-pc-windows-msvc
          #   name: windows-x86_64
          #   binary_path: target/release/llm_dataset_builder.exe
          #   asset_name: llm_dataset_builder-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          
      - name: Compress binary
        if: matrix.os != 'windows-2022'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.asset_name }}.tar.gz llm_dataset_builder
          cd ../../..

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: matrix.os != 'windows-2022'
        with:
          tag_name: v${{ needs.create-release.outputs.version }}
          files: ${{ matrix.asset_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
